//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a resource generator.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Windows.ApplicationModel.Resources;

namespace XboxMediaRemote.App.Resources 
{
    public static class Strings 
	{
        public static ResourceLoader ResourceLoader 
		{ 
			get; private set; 
		}

        static Strings() 
		{
            ResourceLoader = new ResourceLoader();
        }

		public static string Get(string resource)
		{
			return ResourceLoader.GetString(resource); 
		}

		public static string Format(string resource, params object[] args)
		{
			return String.Format(ResourceLoader.GetString(resource), args);
		}

        public static string AboutTitleText 
		{
            get 
			{ 
				return ResourceLoader.GetString("AboutTitle/Text"); 
			}
        }

        public static string AuthorCaptionText 
		{
            get 
			{ 
				return ResourceLoader.GetString("AuthorCaption/Text"); 
			}
        }

        public static string AuthorTitleText 
		{
            get 
			{ 
				return ResourceLoader.GetString("AuthorTitle/Text"); 
			}
        }

        public static string BrowseFolderEmptyText 
		{
            get 
			{ 
				return ResourceLoader.GetString("BrowseFolderEmpty/Text"); 
			}
        }

        public static string CreditsTitleText 
		{
            get 
			{ 
				return ResourceLoader.GetString("CreditsTitle/Text"); 
			}
        }

        public static string GroupFolders 
		{
            get 
			{ 
				return ResourceLoader.GetString("GroupFolders"); 
			}
        }

        public static string GroupMusic 
		{
            get 
			{ 
				return ResourceLoader.GetString("GroupMusic"); 
			}
        }

        public static string GroupOther 
		{
            get 
			{ 
				return ResourceLoader.GetString("GroupOther"); 
			}
        }

        public static string GroupsNumberTitle 
		{
            get 
			{ 
				return ResourceLoader.GetString("GroupsNumberTitle"); 
			}
        }

        public static string GroupsPictures 
		{
            get 
			{ 
				return ResourceLoader.GetString("GroupsPictures"); 
			}
        }

        public static string GroupsSymbolTitle 
		{
            get 
			{ 
				return ResourceLoader.GetString("GroupsSymbolTitle"); 
			}
        }

        public static string GroupVideos 
		{
            get 
			{ 
				return ResourceLoader.GetString("GroupVideos"); 
			}
        }

        public static string MediaHubTitleText 
		{
            get 
			{ 
				return ResourceLoader.GetString("MediaHubTitle/Text"); 
			}
        }

        public static string MediaSearchPlaceholderText 
		{
            get 
			{ 
				return ResourceLoader.GetString("MediaSearch/PlaceholderText"); 
			}
        }

        public static string MediaTypeAudio 
		{
            get 
			{ 
				return ResourceLoader.GetString("MediaTypeAudio"); 
			}
        }

        public static string MediaTypeImage 
		{
            get 
			{ 
				return ResourceLoader.GetString("MediaTypeImage"); 
			}
        }

        public static string MediaTypeVideo 
		{
            get 
			{ 
				return ResourceLoader.GetString("MediaTypeVideo"); 
			}
        }

        public static string PlayToInvalidMediaType 
		{
            get 
			{ 
				return ResourceLoader.GetString("PlayToInvalidMediaType"); 
			}
        }

        public static string PlayToNoFile 
		{
            get 
			{ 
				return ResourceLoader.GetString("PlayToNoFile"); 
			}
        }

        public static string PlayToNoMediaCaptionText 
		{
            get 
			{ 
				return ResourceLoader.GetString("PlayToNoMediaCaption/Text"); 
			}
        }

        public static string PlayToNoMediaTitleText 
		{
            get 
			{ 
				return ResourceLoader.GetString("PlayToNoMediaTitle/Text"); 
			}
        }

        public static string PrivacyPolicyContentText 
		{
            get 
			{ 
				return ResourceLoader.GetString("PrivacyPolicyContent/Text"); 
			}
        }

        public static string SearchResultsHeaderText 
		{
            get 
			{ 
				return ResourceLoader.GetString("SearchResultsHeader/Text"); 
			}
        }

        public static string SearchResultsNoneText 
		{
            get 
			{ 
				return ResourceLoader.GetString("SearchResultsNone/Text"); 
			}
        }

        public static string SettingsAbout 
		{
            get 
			{ 
				return ResourceLoader.GetString("SettingsAbout"); 
			}
        }

        public static string SettingsPrivacyPolicy 
		{
            get 
			{ 
				return ResourceLoader.GetString("SettingsPrivacyPolicy"); 
			}
        }

        public static string WelcomeAppText 
		{
            get 
			{ 
				return ResourceLoader.GetString("WelcomeApp/Text"); 
			}
        }

        public static string WelcomeSubheaderText 
		{
            get 
			{ 
				return ResourceLoader.GetString("WelcomeSubheader/Text"); 
			}
        }

        public static string WelcomeTitleText 
		{
            get 
			{ 
				return ResourceLoader.GetString("WelcomeTitle/Text"); 
			}
        }

        public static string MediaSortAlphabetical 
		{
            get 
			{ 
				return ResourceLoader.GetString("MediaSortAlphabetical"); 
			}
        }

        public static string MediaSortDateCreated 
		{
            get 
			{ 
				return ResourceLoader.GetString("MediaSortDateCreated"); 
			}
        }

        public static string MediaSortType 
		{
            get 
			{ 
				return ResourceLoader.GetString("MediaSortType"); 
			}
        }

    }
}
